### ISSUE TITLE
Bump for python 3.9

### ISSUE THREAD

**Issue by telemmaite** [redis/hiredis-py#101]
Can we bump to 3.9? 
It works fine when building from source and installing (hiredis 1.1.0).

**Comment by ifduyue** [comment]
OK, will be available in the next release

**Comment by HassanAbouelela** [comment]
Sorry to bump this issue, but I was looking at your CI pipelines, and everything seemed to build fine. I'm not familiar with your release procedure, so I don't know how easy this question will be to answer, but do you have an ETA on when the next version will be released?

Thanks

**Comment by ifduyue** [comment]
@HassanAbouelela Next week probably. First 1.1.1, and then 2.0.0a0.

**Comment by HassanAbouelela** [comment]
Awesome, thanks for the update, and good luck.
