### ISSUE TITLE
Wheel support for linux aarch64 [arm64]

### ISSUE THREAD

**Issue by odidev** [redis/hiredis-py#102]
Summary
Installing hiredis-py on aarch64 via pip using command "pip3 install hiredis-py" tries to build wheel from source code

Problem description
hiredis-py doesn't have wheel for aarch64 on PyPI repository. So, while installing hiredis-py via pip on aarch64, pip builds wheel for same resulting in it takes more time to install hiredis-py. Making wheel available for aarch64 will benefit aarch64 users by minimizing hiredis-py installation time.

Expected Output
Pip should be able to download hiredis-py wheel from PyPI repository rather than building it from source code.

@hiredis-py-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make hiredis-py wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by odidev** [comment]
Manylinux2014 ensures that the wheel is built against the AArch64 v8.0 specification. All AArch64 platforms in the v8 series maintain backward compatibility with v8.0. So a binary built for v8.0 can run on any v8 platform. Enabling aarch64 wheel support will benefit arm v8 series users by reducing installation time. Can you please let me know if you have any interest in releasing aarch64 wheels?

**Comment by ifduyue** [comment]
@odidev PR is welcome. Wheels are built on Travis-CI and appveyor.

**Comment by odidev** [comment]
Looks like changes for releasing aarch64 wheels are already shipped in PR: https://github.com/redis/hiredis-py/pull/98. It just needs to trigger the release. I can see the last release for hiredis was made on july 15, 2020. Can you please let me know when the next release is scheduled. If it is going to take time, can you please release aarch64 wheel as part of current release(hiredis 1.1.0).

**Comment by ifduyue** [comment]
> If it is going to take time, can you please release aarch64 wheel as part of current release(hiredis 1.1.0).

No, this will break many projects' builds. New tag only.

**Comment by kapilt** [comment]
why would producing wheels for aarch64 break a project's build?, pip installation will respect arch when downloading

**Comment by ifduyue** [comment]
@kapilt see https://github.com/redis/hiredis-py/issues/69

**Comment by odidev** [comment]
Can you please let me know when the next release is scheduled?

**Comment by ifduyue** [comment]
@odidev v2.0.0 just released

**Comment by odidev** [comment]
Thanks for releasing the AArch64 wheels.
