### ISSUE TITLE
C99 errors with older gcc

### ISSUE THREAD

**Issue by minusf** [redis/hiredis-py#127]
on centos7 `pip install hiredis` fails with multiple errors of this class:

```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ivendor -I/export/gitlab-runner/builds/stxz_Jrf/0/ws/www/venv/include -I/home/webmaster/opt/include/python3.10 -c vendor/hiredis/read.c -o build/temp.linux-x86_64-3.10/vendor/hiredis/read.o
      vendor/hiredis/read.c: In function ‘redisReaderFree’:
      vendor/hiredis/read.c:646:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
               for (int i = 0; i < r->tasks; i++) {
               ^
      vendor/hiredis/read.c:646:9: note: use option -std=c99 or -std=gnu99 to compile your code
      error: command '/usr/bin/gcc' failed with exit code 1
```

Please have merci on us stuck in older corporate environments 😢

**Comment by minusf** [comment]
oh i see this was already fixed
https://github.com/redis/hiredis-py/commit/d4d701a06560ce76a4eaba3ac309ff70e37b3190

would it be possible please to push out a new minor release with the fix?
thank you.

**Comment by jberclaz** [comment]
A new release would be helpful.

**Comment by chayim** [comment]
WDYT folks, is this fair to close with #136 ? Wheels wheels wheels galore are being built.

**Comment by chayim** [comment]
Looks like it's been a minute... we have one "heart". I'm closing. Please feel free to comment here if I was too rash!
