### ISSUE TITLE
Support garbage collection in Reader

### ISSUE THREAD

**Issue by oranav** [redis/hiredis-py#162]
Reader object may hold references to non-primitive objects, such as through `replyError`; therefore, [it must support garbage collection](https://docs.python.org/3/c-api/gcsupport.html#supporting-cycle-detection), which it does not right now.

This may lead to memory leaks, such as happened in <https://github.com/redis/redis-py/issues/2693>.

**Comment by chayim** [comment]
Closed by the merge of #162.
