### ISSUE TITLE
Hiredis cannot be installed on Python 3.13

### ISSUE THREAD

**Issue by wuliao6688** [redis/hiredis-py#186]
Hiredis cannot be installed on Python 3.13

**Comment by tishun** [comment]
Hey @wuliao6688,
hiredis-py requires Python 3.7+ as per the documentation.

**Comment by einarwar** [comment]
Python 3.13 is out now. Any updates on this?

**Comment by monosans** [comment]
Looking forward to Python 3.13 wheels on PyPI
