### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by hxyannay** [redis/hiredis-py#201]
Hey,
Is it possible to release new wheels for hiredis with python 3.13?
Thanks in advance!

**Comment by douglasmiranda** [comment]
Related: #199

**Comment by DeD1rk** [comment]
This can be closed since #199 is now merged.

**Comment by hxyannay** [comment]
Hey,
Thank you very much for that PR :)
I will close this issue once a new release will be made and the wheels will actually be available.

**Comment by hxyannay** [comment]
New release was made, closing.
Thanks @vladvildanov !
