### ISSUE TITLE
Got "TypeError: must be convertible to a buffer, not bytearray" in PyPy

### ISSUE THREAD

**Issue by ethe** [redis/hiredis-py#37]
PyPy version: 4.0.1 with GCC 4.8.4 on linux2
System: Ubuntu 15.04 x86 64bit
Error line: `./site-packages/redis/connection.py` `line 359` `self._reader.feed(self._buffer, 0, bufflen)`

Find where define attribute _reader: `line 313` `self._reader = hiredis.Reader(**kwargs)`, so I think this might be a hiredis problem.
self._buffer's type: `line 292` `self._buffer = bytearray(socket_read_size)`

I tried to change `self._reader`'s type, do like this: `self._reader.feed(buffer(self._buffer), 0, bufflen)`, but if i do this, process would crash.

Now I just move hiredis out, redis clients works no problem.

**Comment by badboy** [comment]
Please tell me how to reproduce it

**Comment by ethe** [comment]
I'm testing now, I think that's a problem for [redis-py](https://github.com/andymccurdy/redis-py) instead of hiredis-py
