### ISSUE TITLE
Add wheel to PYPI package.

### ISSUE THREAD

**Issue by pahaz** [redis/hiredis-py#38]
http://pythonwheels.com/

**Comment by AraHaan** [comment]
Yeah, if there was binary wheels out up to and including python 3.6 it would be of help for Windows, MAC, and linux users.

**Comment by and800** [comment]
at least for amd64 linux, because currently most of internet use ~AWS~ this architecture

**Comment by pahaz** [comment]
Any news about this issues? Is the hiredis maintained?

**Comment by badboy** [comment]
More or less. But I’m on vacation, so don’t expect an update anytime soon.

**Comment by eamigo86** [comment]
Any progress with this???

**Comment by macropin** [comment]
What needs to be done here? I'm happy to help make this happen!

**Comment by eamigo86** [comment]
Hi @macropin, I was just wondering if there was a wheel package for Windows and python<=3.6?

**Comment by ifduyue** [comment]
manylinux1 wheels have been uploaded to pypi.org https://pypi.org/project/hiredis/0.2.0/#files

**Comment by ifduyue** [comment]
wheels for Windows and Mac OS X have been published.
