### ISSUE TITLE
PyPy Compatability

### ISSUE THREAD

**Issue by andymccurdy** [redis/hiredis-py#41]
I was researching an issue a user reported to andymccurdy/redis-py#708 about some issues with hiredis and PyPy version 4.0.1 (and likely other versions of PyPy).

hiredis-py's feed method isn't able to accept `bytearray` objects running on PyPy. This test (https://github.com/redis/hiredis-py/blob/master/test/reader.py#L168) in hiredis-py's test suite fails running on PyPy testing this exact issue. It produces the following traceback:

```
Traceback (most recent call last):
  File "/Users/andy/hiredis-py/test/reader.py", line 170, in test_feed_bytearray
    self.reader.feed(bytearray(b"+ok\r\n"))
TypeError: must be convertible to a buffer, not bytearray
```

While trying to get hiredis-py's test suite to run on PyPy, I also found two other tests (https://github.com/redis/hiredis-py/blob/master/test/reader.py#L133-L139) that cause the test runner to segfault with the following output:

```
<andy@shockwave: ~hiredis-py (master)> python test.py
.................Fatal error in cpyext, CPython compatibility layer, calling PyList_CheckExact
Either report a bug or consider not using this particular extension
<OpErrFmt object at 0x1074432e0>
RPython traceback:
  File "pypy_module_cpyext_api_2.c", line 21254, in PyPyList_CheckExact
  File "pypy_module_cpyext_pyobject.c", line 2094, in BaseCpyTypedescr_realize
  File "pypy_objspace_std_objspace.c", line 4537, in allocate_instance__W_ObjectObject
  File "pypy_objspace_std_typeobject.c", line 4354, in W_TypeObject_check_user_subclass
Segmentation fault: 11
```

**Comment by badboy** [comment]
I never used PyPy and have absolutely no experience with it. Additionally I have only limited time and this is not my priority. 
So for now I have to rely on patches to make it work.

**Comment by thedrow** [comment]
We can use https://github.com/hodgestar/hiredis-cffi as an example.
The callback usage should be converted to new style callbacks though.
