### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by adityapatadia** [redis/hiredis-py#51]
Last version released was 2 years ago. Please release new version so we can use it in production environment.

**Comment by badboy** [comment]
Hm, indeed I never published a release after upgrading hiredis. I should do that eventually.

However, nothing stops you from using the already released version in production

**Comment by nooperpudd** [comment]
Indeed need to release latest version such as wheels to support windows mac, linux.

**Comment by adityapatadia** [comment]
I see there is so much activity on commit side but nothing on release side.

**Comment by blopker** [comment]
@badboy, would you be interested in a PR that has Travis do releases? You can tell Travis whenever a new tag is made on `master` to compile and push to PyPi. I set up something similar for my packages. See https://github.com/23andMe/Yamale#releasing for an example release workflow.

Example Travis config here: https://github.com/23andMe/Yamale/blob/master/.travis.yml

Hopefully that will ease the pain of releasing. We'd really like to use the new code!

**Comment by blopker** [comment]
Also, instructions from Travis here: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by badboy** [comment]
@blopker absolutely. More stuff done by computers = less stuff for me to forget or mess up.
I won’t get to it in the next 2 weeks though

**Comment by nooperpudd** [comment]
What's going on?

**Comment by ifduyue** [comment]
v0.3.0 released https://pypi.org/project/hiredis/0.3.0/
