### ISSUE TITLE
build_ext:  cannot find -lhiredis_for_hiredis_py

### ISSUE THREAD

**Issue by nbonnotte** [redis/hiredis-py#55]
Hi, 

`pip install hiredis --global-option=build_ext` fails for me on both Ubuntu and CentOS.

I understand that `hiredis_for_hiredis_py` should refer to files in `vendor/hiredis/`? Am I doing something wrong?

Thanks!

**Comment by badboy** [comment]
Not really enough info to work with. Please reopen if this is still an issue.
