### ISSUE TITLE
build hiredis failed with Python3.6.2 macOS

### ISSUE THREAD

**Issue by DheerajAgarwal** [redis/hiredis-py#62]
Hi, 

can't install hiredis which fails at building wheel. Please advise.

`wheel                     0.29.0           py36h3597b6d_1`

```
pip install hiredis
Collecting hiredis
  Using cached hiredis-0.2.0.tar.gz
Building wheels for collected packages: hiredis
  Running setup.py bdist_wheel for hiredis ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/yy/_lh_xrrx7r92m999snj4dt1nvs_f1b/T/pip-build-im8m7cxh/hiredis/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/yy/_lh_xrrx7r92m999snj4dt1nvs_f1b/T/tmplgz4f1q6pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/hiredis
  copying hiredis/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/hiredis
  copying hiredis/version.py -> build/lib.macosx-10.9-x86_64-3.6/hiredis
  running build_clib
  building 'hiredis_for_hiredis_py' library
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/vendor
  creating build/temp.macosx-10.9-x86_64-3.6/vendor/hiredis
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -c vendor/hiredis/read.c -o build/temp.macosx-10.9-x86_64-3.6/vendor/hiredis/read.o
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -c vendor/hiredis/sds.c -o build/temp.macosx-10.9-x86_64-3.6/vendor/hiredis/sds.o
  x86_64-apple-darwin13.4.0-ar rc build/temp.macosx-10.9-x86_64-3.6/libhiredis_for_hiredis_py.a build/temp.macosx-10.9-x86_64-3.6/vendor/hiredis/read.o build/temp.macosx-10.9-x86_64-3.6/vendor/hiredis/sds.o
  unable to execute 'x86_64-apple-darwin13.4.0-ar': No such file or directory
  error: command 'x86_64-apple-darwin13.4.0-ar' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for hiredis
```

**Comment by badboy** [comment]
`unable to execute 'x86_64-apple-darwin13.4.0-ar': No such file or directory`

You need a working development environment, including a compiler, linker and other necessary tools. I don't use a Mac and thus have no idea what to install, but probably `xcode` is a good answer here.

**Comment by DheerajAgarwal** [comment]
I have xcode, and other development tools. I was trying to run this in a virtual environment when I ran into this issue. I have subsequently tried it on root and still the same.

**Comment by DheerajAgarwal** [comment]
Actually I have `x86_64-apple-darwin16.7.0` which from Xcode9. Looks like the redis is looking for an older version. As per [Xcode clang version](https://gist.github.com/yamaya/2924292), looks like redis (or wheel) is looking for # Xcode 6.0.1 (6A317) Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)

**Comment by badboy** [comment]
I don't use any macos, so I can't really help with your problem, sorry.

**Comment by badboy** [comment]
@piotrgrundas That's actually a completely different error. Looks like you're missing the required python development package. Run

```
apt-get install python3-dev 
```

**Comment by SURUPAM** [comment]
when i runed it it showing cli.exe error no such file  on windows

C:\cointrol>pip install hiredis
Collecting hiredis
  Using cached hiredis-0.2.0.tar.gz
Building wheels for collected packages: hiredis
  Running setup.py bdist_wheel for hiredis ... error
  Complete output from command c:\users\surupamchandra\appdata\local\programs\py
thon\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\
\SURUPA~1\\AppData\\Local\\Temp\\pip-build-kz1f68iz\\hiredis\\setup.py';f=getatt
r(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close(
);exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\SURUPA~1\AppDat
a\Local\Temp\tmp2wa0by5tpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\hiredis
  copying hiredis\version.py -> build\lib.win-amd64-3.6\hiredis
  copying hiredis\__init__.py -> build\lib.win-amd64-3.6\hiredis
  running build_clib
  building 'hiredis_for_hiredis_py' library
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\vendor
  creating build\temp.win-amd64-3.6\vendor\hiredis
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD /Tcvendor/hiredis/read.c /Fobuild\t
emp.win-amd64-3.6\vendor/hiredis/read.obj
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for hiredis
  Running setup.py clean for hiredis
Failed to build hiredis
Installing collected packages: hiredis
  Running setup.py install for hiredis ... error
    Complete output from command c:\users\surupamchandra\appdata\local\programs\
python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\User
s\\SURUPA~1\\AppData\\Local\\Temp\\pip-build-kz1f68iz\\hiredis\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SURUPA~1\Ap
pData\Local\Temp\pip-ddiiiypw-record\install-record.txt --single-version-externa
lly-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\hiredis
    copying hiredis\version.py -> build\lib.win-amd64-3.6\hiredis
    copying hiredis\__init__.py -> build\lib.win-amd64-3.6\hiredis
    running build_clib
    building 'hiredis_for_hiredis_py' library
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\vendor
    creating build\temp.win-amd64-3.6\vendor\hiredis
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD /Tcvendor/hiredis/read.c /Fobuild
\temp.win-amd64-3.6\vendor/hiredis/read.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------
Command "c:\users\surupamchandra\appdata\local\programs\python\python36\python.e
xe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SURUPA~1\\AppData\\Lo
cal\\Temp\\pip-build-kz1f68iz\\hiredis\\setup.py';f=getattr(tokenize, 'open', op
en)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, _
_file__, 'exec'))" install --record C:\Users\SURUPA~1\AppData\Local\Temp\pip-ddi
iiypw-record\install-record.txt --single-version-externally-managed --compile" f
ailed with error code 1 in C:\Users\SURUPA~1\AppData\Local\Temp\pip-build-kz1f68
iz\hiredis\

C:\cointrol>

**Comment by badboy** [comment]
@SURUPAM You're not on macOS, so again this is a different problem.
`error: command 'cl.exe' failed: No such file or directory` -> You're missing the required build tools. I don't use Windows and thus don't know what to install, but at least a C++ compiler and linker is needed.

**Comment by mohammadtetouan** [comment]
hi , salam 
but i don't want to install Visual C++ because it takes a lot of space 

 Failed building wheel for hiredis
  Running setup.py clean for hiredis
Successfully built msgpack
Failed to build hiredis
Installing collected packages: hiredis, aioredis, msgpack, channels-redis
  Running setup.py install for hiredis ... error
    Complete output from command d:\apps\channels_tut\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mohammad\\AppData\\Local\\Temp\\pip-build-6fjjpprm\\hiredis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mohammad\AppData\Local\Temp\pip-54c9goms-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\apps\channels_tut\env\include\site\python3.6\hiredis:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\hiredis
    copying hiredis\version.py -> build\lib.win32-3.6\hiredis
    copying hiredis\__init__.py -> build\lib.win32-3.6\hiredis
    running build_clib
    building 'hiredis_for_hiredis_py' library
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by mohammadtetouan** [comment]
salam 
``
if there is any other solution instead of installing Visual C++
because it takes alot of disk space 
`Failed building wheel for hiredis
  Running setup.py clean for hiredis
Successfully built msgpack
Failed to build hiredis
Installing collected packages: hiredis, aioredis, msgpack, channels-redis
  Running setup.py install for hiredis ... error
    Complete output from command d:\apps\channels_tut\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mohammad\\AppData\\Local\\Temp\\pip-build-6fjjpprm\\hiredis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mohammad\AppData\Local\Temp\pip-54c9goms-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\apps\channels_tut\env\include\site\python3.6\hiredis:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\hiredis
    copying hiredis\version.py -> build\lib.win32-3.6\hiredis
    copying hiredis\__init__.py -> build\lib.win32-3.6\hiredis
    running build_clib
    building 'hiredis_for_hiredis_py' library
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
`

**Comment by ifduyue** [comment]
I'm going to close this. If there's a problem, please open a new issue.
