### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by badboy** [redis/hiredis-py#63]
I have neither the time nor the energy to fulfil the maintainer role here.
I failed to spend enough time in the past and haven't pushed out a release in nearly 3 years.

If anyone is actively using this project and wants to take over, please reach me over email.

**Comment by nooperpudd** [comment]
cool.

**Comment by ly0** [comment]
👍

**Comment by langsiji** [comment]
let it go

**Comment by pclumson1** [comment]
I would like to contribute to maintain this repos.

Please add me as it currently need maintainance to accomodate with python3.10 and django 4.00

**Comment by badboy** [comment]
Back in 2018 I added @ifduyue as a maintainer.
Recently @illia-v stepped up and asked to help out. Adding them as another maintainer now.

**Comment by badboy** [comment]
huh, turns out I don't actually have admin rights here, so I can't do that.

**Comment by rth** [comment]
@badboy Thanks for following up on this! Do you know anyone in the redis org who could be contacted on this topic?

**Comment by badboy** [comment]
> @badboy Thanks for following up on this! Do you know anyone in the redis org who could be contacted on this topic?

Yup, I reached out to them and working with them to get new people added.

**Comment by badboy** [comment]
https://fnordig.de/2022/11/06/state-of-maintenance-hiredis-py/

@Chayim has pypi access now and I asked them to add @illia-v as well.
Closing this as complete from my side.
