### ISSUE TITLE
New 0.2.0 packages uploaded to PyPi 

### ISSUE THREAD

**Issue by synasius** [redis/hiredis-py#69]
Sorry to open an issue but new packages for the 0.2.0 version have been pushed to pypi and we have checks on file hashes failing in CI. 

Can this release be trusted?

**Comment by csdev** [comment]
we are encountering the same issue:
```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    hiredis==0.2.0 from https://files.pythonhosted.org/packages/52/93/3499eac0cbdc007496c6599d508cda76dc673ce69b6ae778008aa56bf14a/hiredis-0.2.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=45887ded08a2e819123124b5cec4ec1c7e272a8c453d35fecb6d36e5b8c54717 (from -r /opt/bamx/conf/base/requirements.txt (line 329)):
        Expected sha256 ca958e13128e49674aa4a96f02746f5de5973f39b57297b84d59fd44d314d5b5
             Got        45887ded08a2e819123124b5cec4ec1c7e272a8c453d35fecb6d36e5b8c54717
```

**Comment by synasius** [comment]
Exactly that's the same:
```
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may 
have tampered with them.
    hiredis==0.2.0 from https://files.pythonhosted.org/packages/f2/be/e064ff9969d6f0bbdb0c8ee600326e4b3325c33d1703be919aac743d00e7/hiredis-0.2.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=3f8b3
34c59c474e2b92580d7f4fb6503a08c013ae8a877ffc5c252f899d90ac6 (from -r /tmp/pipenv-i5zmpc40-requirements/pipenv-k7k3bujv-requirement.txt (line 1)):
        Expected sha256 ca958e13128e49674aa4a96f02746f5de5973f39b57297b84d59fd44d314d5b5
             Got        3f8b334c59c474e2b92580d7f4fb6503a08c013ae8a877ffc5c252f899d90ac6
```

**Comment by ntietz** [comment]
It seems to me like something smells off here. If nothing else, because certain old files are no longer available. In my pip cache: `hiredis-0.2.0-cp36-cp36m-macosx_10_12_x86_64.whl`

Not available on https://pypi.org/project/hiredis/#files anymore, which only shows `hiredis-0.2.0-cp37-cp37m-manylinux1_x86_64.whl` (with many version combinations).

**Comment by ipmb** [comment]
Adding the environment variable `PIP_NO_BINARY=hiredis` to download the source version from 2015. The hash I have for it is:

```json
        "hiredis": {
            "hashes": [
                "sha256:ca958e13128e49674aa4a96f02746f5de5973f39b57297b84d59fd44d314d5b5"
            ],
            "index": "pypi",
            "version": "==0.2.0"
        }
```

**Comment by ipmb** [comment]
https://github.com/redis/hiredis-py/issues/38#issuecomment-413554660

**Comment by synasius** [comment]
@ipmb ok, so it looks like it is a legitimate release. I will update the hashes in our CI and going to close this issue.

**Comment by badboy** [comment]
Thanks for bringing up these valid concerns and sorry for jumping in so late.

I indeed handed over maintainership to @ifduyue a while ago. He has the necessary rights on both github and pypi to work on the code and release new versions.
I still retain the full ownership rights for github and pypi.

As I don't know about how wheels work, please double-check that the content is valid and matches the repository (and report back to me if not, in private).
For now I trust @ifduyue to act in good faith and doing the right thing here.
If anything else comes up, don't hesitate to contact me privately.
