### ISSUE TITLE
Build wheels for Python 3.7.1

### ISSUE THREAD

**Issue by dimaqq** [redis/hiredis-py#76]

**Comment by un-def** [comment]
CPython 3.7 wheels [have already been uploaded to pypi.org](https://pypi.org/project/hiredis/#files): 

> hiredis-0.2.0-cp37-cp37m-manylinux1_i686.whl                                                   
> hiredis-0.2.0-cp37-cp37m-manylinux1_x86_64.whl                  

It should work with any CPython 3.7.x compiled `--with-pymalloc` (enabled by default) on a wide range of modern linux distributions (both 32-bit and 64-bit) — thanks to [manylinux1](https://www.python.org/dev/peps/pep-0513/) platform.

**Comment by ifduyue** [comment]
Like @un-def said, cp37 wheels will work for Python 3.7.1
And now wheels for Mac OS X and Windows are also provided.
