### ISSUE TITLE
hiredis-py ignores string decoding errors

### ISSUE THREAD

**Issue by andymccurdy** [redis/hiredis-py#81]
When an encoding is specified (for instance 'utf8'), hiredis-py will attempt to decode string values using that encoding. If the decode raises a ValueError, hiredis-py will ignore the error and return the original bytes.

In my opinion hiredis-py should instead raise a `UnicodeDecodeError` (or another similar exception) to indicate that the decoding failed. Asking for a decoded string and getting back bytes seems wrong.

Perhaps to mitigate backwards incompatibility issues, a separate `strict` flag could be introduced with a default value of `False`. When `encoding != None && strict==False`, hiredis-py would continue to hide the error and return bytes on error. However when `encoding != None && strict==True`, hiredis-py would raise an error.

I'm happy to put together a PR for this.

**Comment by ifduyue** [comment]
I agree `UnicodeDecodeError` should not be ignored.
We can introduce a `strict` flag, or we can increase the minor number (`0.4.0`) or even increase the major number (`1.0.0`). Don't know which is more suitable. What do you prefer?

**Comment by andymccurdy** [comment]
I think I like introducing a new argument. And I like naming the argument `errors` instead of `strict`. We would then pass the value directly to the `errors` argument of `PyUnicode_Decode`. This matches the behavior of decoding bytes to strings on the Python side and provides the same functionality that users are already used to.

If this value is initialized to `NULL` by default then backwards compatibility is maintained. However I think this promotes bad behavior. In Python 2 and 3, the default value of `errors` is `'strict'` which causes a `UnicodeDecodeError` to be raised on failure. I would be fine making this the default in hiredis-py as well but we then need to increase the version number and inform folks of the possibly breaking change.

Your call on what you want to do re: version numbers/documentation. I'll start working on a PR.

**Comment by andymccurdy** [comment]
@ifduyue Just checking in to see when this might get released to PyPI. Thanks again for merging.

**Comment by ifduyue** [comment]
@andymccurdy later in this weekend

**Comment by ifduyue** [comment]
@andymccurdy v1.0.0 is on PyPI now

**Comment by andymccurdy** [comment]
thanks!
