### ISSUE TITLE
Request: RESP 3 support

### ISSUE THREAD

**Issue by schlitzered** [redis/hiredis-py#84]
hi, i am the author of one of the python redis implementations, and i am currently working on implementing resp3 in my fallback parser.

are there already plans to support RESP 3? if yes how are you planning to implement protocol switching?

this is somehow important because with RESP 3 parsers/clients are expected to return programming language native responses, like dicts, lists or sets.

since i mimic the api of hiredis-py, i would think it would be nice if there is a function to tell the parser to switch protocols.

something like parsert.protocol = 3

what do you think?

Kind regards

**Comment by ifduyue** [comment]
Hello,

Currently no plan to support RESP3.
hiredis-py is a wrapper of [hiredis](https://github.com/redis/hiredis). Unless hiredis supports RESP3, hiredis-py will not support RESP3.

**Comment by bsergean** [comment]
It looks like this PR added RESP3 support to the mainline.

https://github.com/redis/hiredis/pull/697

**Comment by ifduyue** [comment]
Noticed.  I think we need to write a pure python reader if we want to continue the support for windows.

**Comment by bsergean** [comment]
You probably are aware of different pure python reader, but one I know of is embedded in aredis.

(class PythonParser)
https://github.com/NoneGG/aredis/blob/master/aredis/connection.py#L175

There isn't much code it's funny ...

**Comment by ifduyue** [comment]
redis-py has a pure python [parser](https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L291), too

**Comment by ifduyue** [comment]
These two parsers aren't RESP3 yet 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/568900/75345297-6a214680-58d7-11ea-8d02-4ebf8ff238c9.png">

**Comment by bsergean** [comment]
If the hash-table (%) the only addition in the term of data type that you know of for RESP 3 ?

**Comment by michael-grunder** [comment]
[No there are a ton of new types](https://github.com/antirez/RESP3/blob/master/spec.md#resp3-types)

* `,` - DOUBLE
* `_` - NIL
* `%` - MAP
* `~` - SET
* `#` - BOOL
* `!` - BLOB ERROR
* `=` - VERTBATIM STRING
* `(` - BIG NUMBER

**Comment by Harrison88** [comment]
I've been implementing a Python RESP3 parser here, if that's helpful at all: https://github.com/Harrison88/redtrio/blob/master/src/redtrio/lowlevel/protocol.py

**Comment by schlitzered** [comment]
@Harrison88: nice, i will take a look at the implementation later. would you might consider putting the parser into a separate package?

then i could make use of it in https://github.com/schlitzered/pyredis.
