### ISSUE TITLE
Adding type stubs

### ISSUE THREAD

**Issue by sbdchd** [redis/hiredis-py#99]
Was wondering if you'd be open to type stubs being added to the repo if I made a PR

Since the project is in C I think the stubs would need to be in a `.pyi` file.

Also need to add a `py.typed` file to the module so `mypy` and similar type checks know to look for types: https://www.python.org/dev/peps/pep-0561/#packaging-type-information

**Comment by ifduyue** [comment]
@sbdchd It's good to have tyep stubs, PR is welcome.
